apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssup2ket-auth-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: ssup2ket-auth
        image: ssup2/ssup2ket-auth:0.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: SERVER_URL
          value: http://192.168.0.38/auth
        - name: DEPLOY_ENV
          value: prod
        - name: MYSQL_PRIMARY_DATABASE
          value: prod_auth
        - name: MYSQL_SECONDARY_DATABASE
          value: prod_auth

