namespace: app-prod

commonLabels:
  deploy-env: prod

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- gateway.yaml
- virtualservice.yaml
- debezium_deployment.yaml
- debezium_secret.yaml
