apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ssup2ket-auth-virtualservice
spec:
  hosts:
  - "192.168.0.38"
  - prod-ssupket-auth-service
  gateways:
  - prod-ssup2ket-auth-gateway
  http:
  - match:
    - uri:
        prefix: "/auth/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: prod-ssup2ket-auth-service
  - match:
    - port: 9100  
    route:
    - destination:
        host: prod-ssup2ket-auth-service
