apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssup2ket-store-debezium-deployment
spec:
  template:
    spec:
      containers:
      - name: debezium-connector
        env: 
        - name: BOOTSTRAP_SERVERS
          value: kafka-stage.infra:9092
