apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssup2ket-store-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: ssup2ket-store
        image: ssup2/ssup2ket-store:branch-master
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: SERVER_URL
          value: http://192.168.0.36/store
        - name: PROFILE_ACTIVE
          value: stage
        - name: MYSQL_PRIMARY_DATABASE
          value: stage_store
        - name: MYSQL_SECONDARY_DATABASE
          value: stage_store
        - name: KAFKA_CONSUMER_IP
          value: kafka-stage.infra
        - name: KAFKA_CONSUMER_PORT
          value: "9092"

