apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth-deployment
  labels:
    app: service-auth
spec:
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      containers:
      - name: service-auth
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: grpc
          containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: MYSQL_PRIMARY_IP
          value: mysql-primary.infra
        - name: MYSQL_PRIMARY_PORT
          value: "3306"
        - name: MYSQL_PRIMARY_USER
          value: root
        - name: MYSQL_PRIMARY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-auth-secret
              key: MYSQL_PRIMARY_PASSWORD
        - name: MYSQL_SECONDARY_IP
          value: mysql-secondary.infra
        - name: MYSQL_SECONDARY_PORT
          value: "3306"
        - name: MYSQL_SECONDARY_USER
          value: root
        - name: MYSQL_SECONDARY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-auth-secret
              key: MYSQL_SECONDARY_PASSWORD
        - name: JAEGER_COLLECTOR_ENDPOINT
          value: http://jaeger-collector.istio-system:14268/api/traces
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
