apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssup2ket-auth-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: ssup2ket-auth
        image: ssup2/ssup2ket-auth:branch-master
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: SERVER_URL
          value: http://192.168.0.36/auth
        - name: DEPLOY_ENV
          value: stage
        - name: MYSQL_PRIMARY_DATABASE
          value: stage_auth
        - name: MYSQL_SECONDARY_DATABASE
          value: stage_auth

