apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ssup2ket-auth-gateway
spec:
  selector:
    istio: dev-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "192.168.0.36"
