namespace: app-stage

commonLabels:
  deploy-env: stage

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- gateway.yaml
- virtualservice.yaml
- debezium_deployment.yaml
- debezium_secret.yaml
