namespace: app-dev

commonLabels:
  deploy-env: dev

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- gateway.yaml
- virtualservice.yaml
- debezium_deployment.yaml
- debezium_configmap.yaml
