apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-store-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: service-store
        image: ghcr.io/ssup2ket/service-store:branch-master
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SERVER_URL
          value: http://192.168.0.36/store
        - name: KAFKA_TOPIC_PREFIX
          value: stage
        - name: KAFKA_GROUPID_PREFIX
          value: stage
        - name: PROFILE_ACTIVE
          value: stage
        - name: LOGGER_LEVEL
          value: info

