apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssup2ket-store-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: ssup2ket-store
        image: ssup2/ssup2ket-store:0.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: SERVER_URL
          value: http://192.168.0.38/store
        - name: DEPLOY_ENV
          value: prod
        - name: MYSQL_PRIMARY_DATABASE
          value: prod_store
        - name: MYSQL_SECONDARY_DATABASE
          value: prod_store

