apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssup2ket-store-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: ssup2ket-store
        image: ssup2/ssup2ket-store:0.1
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: SERVER_URL
          value: http://192.168.0.38/store
        - name: KAFKA_CONSUMER_IP
          value: kafka-prod.infra
        - name: KAFKA_CONSUMER_PORT
          value: "9092"
        - name: PROFILE_ACTIVE
          value: prod
        - name: LOGGER_LEVEL
          value: info
