apiVersion: v1
kind: ConfigMap
metadata:
  name: ssup2ket-store-debezium-configmap
  labels:
    app: ssup2ket-store-debezium
data:
  log4j.properties: |
    log4j.rootLogger=WARN, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n