apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssup2ket-store-deployment
  labels:
    app: ssup2ket-store
spec:
  selector:
    matchLabels:
      app: ssup2ket-store
  template:
    metadata:
      labels:
        app: ssup2ket-store
    spec:
      containers:
      - name: ssup2ket-store
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: grpc
          containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
        env:
        - name: MYSQL_PRIMARY_IP
          value: mysql-primary.infra
        - name: MYSQL_PRIMARY_PORT
          value: "3306"
        - name: MYSQL_PRIMARY_USER
          value: root
        - name: MYSQL_PRIMARY_PASSWORD
          value: root
        - name: MYSQL_SECONDARY_IP
          value: mysql-secondary.infra
        - name: MYSQL_SECONDARY_PORT
          value: "3306"
        - name: MYSQL_SECONDARY_USER
          value: root
        - name: MYSQL_SECONDARY_PASSWORD
          value: root     
        - name: JAEGER_ENDPOINT
          value: http://zipkin.istio-system:9411
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
